// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"github.com/0xjasoncao/gin-scaffold/configs/config"
	"github.com/0xjasoncao/gin-scaffold/internal/apis/handler"
	"github.com/0xjasoncao/gin-scaffold/internal/apis/handler/V1/user"
	"github.com/0xjasoncao/gin-scaffold/internal/apis/router"
	"github.com/0xjasoncao/gin-scaffold/internal/bootstrap/provider"
	"github.com/google/wire"
)

// Injectors from wire.go:

func BuildInjector(config2 *config.Config) (*ApiInjector, func(), error) {
	userHandler := user.NewUserHandler()
	v1 := &handler.V1{
		User: userHandler,
	}
	handlerHandler := &handler.Handler{
		V1: v1,
	}
	redis, cleanup := provider.InitRedisCli(config2)
	memory, cleanup2 := provider.InitMemoryCache()
	service, cleanup3, err := provider.InitTokenService(config2, redis, memory)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	engine := router.NewRouter(config2, handlerHandler, service)
	apiInjector := &ApiInjector{
		Engine: engine,
	}
	return apiInjector, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var RepoProviderSet = wire.NewSet()

var HandlerProviderSet = wire.NewSet(user.NewUserHandler, wire.Struct(new(handler.V1), "*"), wire.Struct(new(handler.Handler), "*"))

var ProviderSet = wire.NewSet(provider.BasicProviderSet, router.NewRouter, RepoProviderSet,
	HandlerProviderSet, wire.Struct(new(ApiInjector), "*"),
)
