definitions:
  core.OrderDirection:
    enum:
    - 1
    - 2
    type: integer
    x-enum-varnames:
    - OrderByASC
    - OrderByDESC
  core.OrderField:
    properties:
      key:
        type: string
      order:
        $ref: '#/definitions/core.OrderDirection'
    type: object
  core.Pagination:
    properties:
      current:
        description: Current Page
        type: integer
      pageSize:
        description: Page Size
        type: integer
      total:
        description: Total count
        type: integer
    type: object
  ginutil.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
      meta: {}
      success:
        type: boolean
    type: object
  request.LoginRequest:
    properties:
      email:
        type: string
      password:
        maxLength: 16
        minLength: 6
        type: string
      verify_code:
        type: string
    required:
    - email
    - password
    - verify_code
    type: object
  request.RoleCreateRequest:
    properties:
      comment:
        type: string
      name:
        type: string
    required:
    - name
    type: object
  request.RoleDeleteRequest:
    properties:
      ids:
        items:
          type: integer
        minItems: 1
        type: array
    required:
    - ids
    type: object
  request.RoleQueryRequest:
    properties:
      '-':
        description: Pagination
        type: boolean
      current:
        description: Current page
        type: integer
      order_fields:
        items:
          $ref: '#/definitions/core.OrderField'
        maxItems: 5
        type: array
      pageSize:
        description: Page size
        maximum: 100
        type: integer
    type: object
  request.RoleUpdateRequest:
    properties:
      comment:
        type: string
      id:
        type: integer
      name:
        type: string
    required:
    - id
    - name
    type: object
  response.LoginResponse:
    properties:
      gender:
        type: integer
      id:
        type: integer
      nick_name:
        type: string
      token_info:
        $ref: '#/definitions/token.IssuingTokenInfo'
      user_name:
        type: string
    type: object
  response.RoleQueryResponse:
    properties:
      comment:
        type: string
      created_at:
        description: CreatedAt
        type: string
      id:
        type: integer
      name:
        type: string
      status:
        type: integer
      updated_at:
        description: UpdatedAt
        type: string
    type: object
  token.IssuingTokenInfo:
    properties:
      access_token:
        description: Access token string
        type: string
      expires_at:
        description: Expiration timestamp (Unix seconds)
        type: integer
      issued_at:
        description: Issue timestamp (Unix seconds)
        type: integer
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
paths:
  /system/role/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: 创建参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.RoleCreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 创建成功
          schema:
            $ref: '#/definitions/ginutil.Response'
      summary: 创建角色
      tags:
      - 角色
  /system/role/delete:
    post:
      consumes:
      - application/json
      parameters:
      - description: 删除参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.RoleDeleteRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 删除成功
          schema:
            $ref: '#/definitions/ginutil.Response'
      summary: 删除角色
      tags:
      - 角色
  /system/role/query:
    get:
      consumes:
      - application/json
      parameters:
      - description: 查询参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.RoleQueryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/ginutil.Response'
            - properties:
                Data:
                  items:
                    $ref: '#/definitions/response.RoleQueryResponse'
                  type: array
                Meta:
                  $ref: '#/definitions/core.Pagination'
              type: object
      summary: 查询角色列表
      tags:
      - 角色
  /system/role/update:
    post:
      consumes:
      - application/json
      parameters:
      - description: 编辑参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.RoleUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 编辑成功
          schema:
            $ref: '#/definitions/ginutil.Response'
      summary: 编辑角色
      tags:
      - 角色
  /system/user/login/:
    post:
      consumes:
      - application/json
      description: login
      parameters:
      - description: 登录参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/ginutil.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.LoginResponse'
              type: object
      summary: 登录
      tags:
      - 用户
  /system/user/logout:
    post:
      consumes:
      - application/json
      parameters:
      - description: access_token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ginutil.Response'
      summary: 登出
      tags:
      - 用户
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
